# include: ['dokumentit']
title: Piraattipuolueen dokumenttikirjasto
description: >
  GitHub Pagesissa yll채pidetty Piraattipuolueen historian
  s채ilytt채v채 dokumenttikirjasto.
lang: fi
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

theme: minima
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-minimal
