# include: ['dokumentit']
title: Piraattipuolueen dokumenttikirjasto
description: >
  GitHub Pagesissa yll채pidetty Piraattipuolueen historian
  s채ilytt채v채 dokumenttikirjasto.
lang: fi
icon: https://www.piraattipuolue.fi/wp-content/uploads/2016/10/cropped-2000px-Piratpartiet.svg_-32x32.png
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

theme: minima
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-minimal
